### ISSUE TITLE
Maintenance TODO List

### ISSUE THREAD

**Issue by lishaduck** [jfmengels/node-elm-review#169]
@jfmengels, can you confirm these are all reasonable?

## Now

- [ ] Land #168 (it's 99.99% complete locally, just have to rebase some stuff and check eslint still passes)

## Soon

- [ ] Refactor help messages (from #126)
- [ ] Replace fs-extra (#120/#147)
- [ ] Run Knip on the codebase to find unused code.
- [ ] Bump Pretter to v3
- [ ] Run `npm dedupe` to clean up the `package-lock.json` (should we be using an `npm-shrinkwrap.json`?)
- [ ] Run GHA in a matrix to catch incompatibility issues faster.
- [ ] Make some GHA security fixes.
- [ ] Update GHA dependencies.

## Relatively soon

- [ ] Add TS types for everything (#155 is a good starting point)
- [ ] Enabler stricter TSESLint rules.
- [ ] Enable [eslint-plugin-perfectionist](https://github.com/azat-io/eslint-plugin-perfectionist)? (~helps object monomorphization, which should help perf very slightly)
- [ ] [`eslint-plugin-no-use-extend-native`](https://www.npmjs.com/package/eslint-plugin-no-use-extend-native) to prevent messing with messed up prototypes (from XO)
- [ ] [`eslint-plugin-import-x`](https://www.npmjs.com/package/eslint-plugin-import-x) a faster `eslint-plugin-import` with fewer dependencies (the original is from XO)

## Someday

- [ ] ESM? Node 12+ supports it, so we could migrate now.

**Comment by jfmengels** [comment]
These all sound good to me.

I don't know if we want a shrinkwrap though. Back in the days that was only recommended for applications. I haven't heard of that advice changing but I may not be up to date.

Maybe let's create separate issues for most of these? At least the ones marked as relatively doon and later?

**Comment by lishaduck** [comment]
> I don't know if we want a shrinkwrap though. Back in the days that was only recommended for applications. I haven't heard of that advice changing but I may not be up to date.

I was thinking of elm-review as an application (it's not a library, so 🤷‍♂️).

> Maybe let's create separate issues for most of these? At least the ones marked as relatively doon and later?

👍

**Comment by jfmengels** [comment]
> > I don't know if we want a shrinkwrap though. Back in the days that was only recommended for applications. I haven't heard of that advice changing but I may not be up to date.

> I was thinking of elm-review as an application (it's not a library, so 🤷‍♂️).

Right, but unless we ship a single binary, the dependencies enforced by our shrinkwrap will likely not be the ones that a user downloads when they download `elm-review`, since our shrinkwrap will not be evaluated. The shrinkwrap in the repo would only be used for development purposes.

**Comment by lishaduck** [comment]
> > > I don't know if we want a shrinkwrap though. Back in the days that was only recommended for applications. I haven't heard of that advice changing but I may not be up to date.
> 
> > I was thinking of elm-review as an application (it's not a library, so 🤷‍♂️).
> 
> Right, but unless we ship a single binary, the dependencies enforced by our shrinkwrap will likely not be the ones that a user downloads when they download `elm-review`, since our shrinkwrap will not be evaluated. The shrinkwrap in the repo would only be used for development purposes.

Oh, is that how it works? Thanks for explaining :)

**Comment by lishaduck** [comment]
Oh, just a small FYI: I've been focusing on some other OSS work recently, and I've just about finished it; however I've been working on my school Mac, but I'll have to return it soon, after which I'll be an old, slow Windows machine. Therefore, I'll probably stop helping out until mid-August. I'll still be around if you need to @mention me, but I probably won't be writing any new PRs (or rebasing old ones).
Have a nice month! "See" you laterish.

**Comment by jfmengels** [comment]
@lishaduck That is absolutely fine. Thank you for the huge amount of work you put in the project, I highly appreciate it :heart: 
And you can come back whenever you want :smile:

**Comment by lishaduck** [comment]
> That is absolutely fine.

Yeah, I just didn't want to seem like I was leaving a bunch of stuff unfinished, I'm just on a brief hiatus.

>Thank you for the huge amount of work you put in the project, I highly appreciate it ❤️

Thanks. I, too, appreciate that.

Bye from a Windows box!

P.S.: If you need Windows testing in the next month or so, just ping me :)
